{{- if .Values.aws.enabled }}
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }}
      name: aws-secret
      key: creds
{{- end }}